name: First pipeline

on:
  push:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: checkout de código
        uses: action/checkout@v5

      - name: Mostrar mensagem
        run: echo "Olá, mundo!"
       